nama = input    ("Nama                 : ")
nim = input     ("NIM                  : ")
kelas = input   ("Kelas Paralel        : ")
TTL = input     ("Tempat/Tanggal Lahir : ")
alamat = input  ("Alamat               : ")
hobby = input   ("Hobby                : ")
HP = input      ("No. HP               : ")

print("\n")
print("Nama                 :", nama)
print("NIM                  :", nim)
print("Kelas Paralel        :", kelas)
print("Tampat/Tanggal Lahir :", TTL)
print("Alamat               :", alamat)
print("Hobby                :", hobby)
print("No. HP               :", HP)
