print("##############################")
print("#                            #")
print("#   Muhammad Irgi Fahrezha   #")
print("#        2410817210005       #")
print("#                            #")
print("##############################")